apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ciliumnetworkpolicies.cilium.io
spec:
  group: cilium.io
  names:
    kind: CiliumNetworkPolicy
    plural: ciliumnetworkpolicies
    shortNames:
    - cnp
    singular: ciliumnetworkpolicy
  scope: Namespaced
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: "Specification of the CNP"
            properties:
              endpointSelector:
                type: object
                description: "EndpointSelector selects all endpoints which should be subject to this rule"
              ingress:
                type: array
                description: "List of ingress rules"
                items:
                  type: object
              egress:
                type: array
                description: "List of egress rules"
                items:
                  type: object
              labels:
                type: array
                description: "Labels is a list of optional strings which can be used to re-identify the rule"
                items:
                  type: string
              description:
                type: string
                description: "Description is a free form string, it can be used by the creator of the rule to store human readable explanation"
          status:
            type: object
            description: "Status is the status of the Cilium policy rule"
            properties:
              nodes:
                type: object
                description: "Nodes is the Cilium policy status for each node"
                additionalProperties:
                  type: object
                  properties:
                    ok:
                      type: boolean
                    error:
                      type: string
                    lastUpdated:
                      type: string
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ciliumclusterwidenetworkpolicies.cilium.io
spec:
  group: cilium.io
  names:
    kind: CiliumClusterwideNetworkPolicy
    plural: ciliumclusterwidenetworkpolicies
    shortNames:
    - ccnp
    singular: ciliumclusterwidenetworkpolicy
  scope: Cluster
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: "Specification of the CCNP"
            properties:
              endpointSelector:
                type: object
                description: "EndpointSelector selects all endpoints which should be subject to this rule"
              nodeSelector:
                type: object
                description: "NodeSelector selects all nodes which should be subject to this rule"
              ingress:
                type: array
                description: "List of ingress rules"
                items:
                  type: object
              egress:
                type: array
                description: "List of egress rules"
                items:
                  type: object
              labels:
                type: array
                description: "Labels is a list of optional strings which can be used to re-identify the rule"
                items:
                  type: string
              description:
                type: string
                description: "Description is a free form string, it can be used by the creator of the rule to store human readable explanation"
          status:
            type: object
            description: "Status is the status of the Cilium policy rule"
            properties:
              nodes:
                type: object
                description: "Nodes is the Cilium policy status for each node"
                additionalProperties:
                  type: object
                  properties:
                    ok:
                      type: boolean
                    error:
                      type: string
                    lastUpdated:
                      type: string
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
