apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-certificate
  namespace: cert-manager
spec:
  secretName: example-certificate-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - FOS1
  commonName: example.fos1.io
  dnsNames:
    - example.fos1.io
    - www.example.fos1.io
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
