apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network

resources:
  - ntp-service-example.yaml
  - ../../base/ntp

commonLabels:
  app.kubernetes.io/part-of: fos1
  app.kubernetes.io/component: ntp
  app.kubernetes.io/managed-by: kustomize
