apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network

resources:
  - crds/wireguard.yaml
  - wireguard-controller.yaml
  - wireguard-daemon.yaml

commonLabels:
  app.kubernetes.io/part-of: fos1
  app.kubernetes.io/component: vpn
  app.kubernetes.io/managed-by: kustomize