apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coredns.yaml
  - adguard.yaml
  - mdns.yaml
  - crds/dnszone.yaml
  - crds/mdnsreflection.yaml
  - crds/dnsclient.yaml
  - crds/dnsfilterlist.yaml
  - crds/ptrzone.yaml