apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ebpfprogram.yaml
  - ebpfmap.yaml
  - ebpfnetworkpolicy.yaml
  - ebpftrafficcontrol.yaml
  - ebpfnatpolicy.yaml
  - ebpfcontainerpolicy.yaml
