apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - certificate-controller.yaml

commonLabels:
  app.kubernetes.io/part-of: fos1
  app.kubernetes.io/component: security
  app.kubernetes.io/managed-by: kustomize
