apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsclients.dns.fos1.io
spec:
  group: dns.fos1.io
  names:
    kind: DNSClient
    listKind: DNSClientList
    plural: dnsclients
    singular: dnsclient
    shortNames:
      - dc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - name
                - addresses
              properties:
                name:
                  type: string
                  description: Client name for identification
                addresses:
                  type: array
                  description: IP addresses of the client
                  items:
                    type: string
                    pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$|^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:)))(%.+)?s*$'
                mac:
                  type: string
                  description: MAC address of the client
                  pattern: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'
                filteringEnabled:
                  type: boolean
                  description: Whether DNS filtering is enabled for this client
                  default: true
                filterLists:
                  type: array
                  description: References to DNSFilterList resources to apply to this client
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: Name of the DNSFilterList resource
                      namespace:
                        type: string
                        description: Namespace of the DNSFilterList resource
                        default: default
                overrides:
                  type: object
                  description: Client-specific filtering overrides
                  properties:
                    allowList:
                      type: array
                      description: Domains to always allow for this client
                      items:
                        type: string
                    blockList:
                      type: array
                      description: Domains to always block for this client
                      items:
                        type: string
                safesearch:
                  type: boolean
                  description: Whether to enforce safe search for this client
                  default: false
                parentalControls:
                  type: object
                  description: Parental control settings
                  properties:
                    enabled:
                      type: boolean
                      description: Whether parental controls are enabled
                      default: false
                    schedule:
                      type: object
                      description: Schedule for parental controls
                      properties:
                        weekdays:
                          type: array
                          description: Days of the week to enforce controls
                          items:
                            type: string
                            enum: [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
                        timeStart:
                          type: string
                          description: Start time in 24h format (HH:MM)
                          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
                        timeEnd:
                          type: string
                          description: End time in 24h format (HH:MM)
                          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
            status:
              type: object
              properties:
                state:
                  type: string
                  description: Current state of this client configuration
                  enum:
                    - Pending
                    - Active
                    - Failed
                    - Unknown
                lastSeen:
                  type: string
                  format: date-time
                  description: Last time this client was seen
                queriesBlocked:
                  type: integer
                  description: Number of DNS queries blocked for this client
                queriesTotal:
                  type: integer
                  description: Total number of DNS queries from this client
                message:
                  type: string
                  description: Status message or error
      additionalPrinterColumns:
        - name: Filtering
          type: boolean
          jsonPath: .spec.filteringEnabled
        - name: Status
          type: string
          jsonPath: .status.state
        - name: LastSeen
          type: string
          jsonPath: .status.lastSeen
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
